name: Typescript

on:
    pull_request:
      branches: [main]
      paths:
        - 'client/**'
    workflow_dispatch:

permissions:
    contents: read

jobs:
    prettier:
        # Check if prettier needs to be applied
        runs-on: ubuntu-latest
        name: Prettier
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  cache-dependency-path: './client/package-lock.json'
                  node-version: '24'

            - name: Install dependencies
              working-directory: ./client
              run: npm install

            - name: Run prettier
              working-directory: ./client
              run: npx prettier package.json "./src/**/*.ts" -c

    eslint:
        runs-on: ubuntu-latest
        name: ESlint
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  cache-dependency-path: './client/package-lock.json'
                  node-version: '24'

            - name: Install dependencies
              working-directory: ./client
              run: npm install

            - name: Run eslint
              working-directory: ./client
              run: npm run lint
    
    test:
      runs-on: ubuntu-latest
      name: Vitest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
              cache: 'npm'
              cache-dependency-path: './client/package-lock.json'
              node-version: '24'

        - name: Install dependencies
          working-directory: ./client
          run: npm install
        
        - name: Run Tests
          working-directory: ./client
          run: npm run test